apiVersion: v1
kind: Service
metadata:
  name: dns-service-udp
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
