apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods
  namespace: prometheus
rules:
- apiGroups:
  - '*'
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-managers
  namespace: prometheus
subjects:
  - kind: ServiceAccount
    name: carol
    namespace: prometheus
    apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-pods
