apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-pods
rules:
- apiGroups:
  - '*'
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-managers
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-pods
