apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: binhex386/frontend-demo
    name: frontend
    resources: {}
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: '0.0.0.0'
    - name: CURRENCY_SERVICE_ADDR
      value: '0.0.0.0'
    - name: CART_SERVICE_ADDR
      value: '0.0.0.0'
    - name: RECOMMENDATION_SERVICE_ADDR
      value: '0.0.0.0'
    - name: CHECKOUT_SERVICE_ADDR
      value: '0.0.0.0'
    - name: SHIPPING_SERVICE_ADDR
      value: '0.0.0.0'
    - name: AD_SERVICE_ADDR
      value: '0.0.0.0'
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
